[package]
name = "read-token-derive"
version = "0.1.0"
authors = ["nanonicholson <nanonicholson@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
